version: 0.1
log:
  level: info
  formatter: text
storage:
  filesystem:
    rootdirectory: /var/lib/registry
delete:
    enabled: true
http:
  addr: localhost:5000
  tls:
    certificate: /certificate.crt
    key: /certificate.key
    clientcas:
      - /ca.crt
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
