version: 0.1
log:
  level: info
  formatter: text
storage:
  filesystem:
    rootdirectory: /var/lib/registry
delete:
    enabled: true
htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
http:
  addr: localhost:5000
  tls:
    certificate: /certs/certificate.crt
    key: /certs/certificate.key
    clientcas:
      - /certs/ca.crt
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
