version: '3.7'

volumes:
  data:

networks:
  app:
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24

services:
  registry:
    image: registry:2.6.2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/certificate.crt
      REGISTRY_HTTP_TLS_KEY: /certs/certificate.key
      REGISTRY_HTTP_TLS_CLIENTCAS: " - /certs/ca.crt"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - data:/data
      - ./.env-files/certificate.crt:/certs/certificate.crt
      - ./.env-files/certificate.key:/certs/certificate.key
      - ./.env-files/ca.crt:/certs/ca.crt
      - ./.secret-files:/auth
    networks:
      app:
        ipv4_address: 172.16.238.10
    restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  cli:
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
    depends_on:
      - registry
    command: ["python", "/task.py"]
    env_file: .env
    volumes:
      - .secret:/.secret:ro
      - ./docker/cli/registry.sh:/./registry.sh
      - ./docker/cli/task.py:/./task.py
      - ./.env-files/certificate.crt:/certs/certificate.crt
      - ./.env-files/certificate.key:/certs/certificate.key
      - ./.env-files/ca.crt:/certs/ca.crt
    extra_hosts:
     - "${DOCKER_REGISTRY_NAME}:172.16.238.10"
    networks:
      app:
    restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
